// -*- Kotlin; generated by gen_test_p1-p4.py, do not hand-edit blindly -*-
package com.lingion.sleepy.data.jw

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * 北京交通大学 (AA, aa.bjtu.edu.cn) 解析器测试 — issue #19, 教务跨仓验证 SOP 2026-09-09。
 * fixture 来自协议 matrix 交叉证实的页面形状 (docs/bjtu-cross-verify-2026-09-09/)。
 */
class JwBjtuParserTest {

    private fun res(name: String): String =
        javaClass.classLoader!!.getResourceAsStream("jw/fixtures/bjtu/$name")!!
            .bufferedReader().use { it.readText() }

    private fun stu() = res("bjtu-stuschedule.sample.html")
    private fun sched() = res("bjtu-schedule.sample.html")
    private fun login() = res("bjtu-login.sample.html")
    private fun zfForeign() = res("bjtu-zf-foreign.sample.html")

    private fun combined(): String =
        JwBjtuParser.DOC_MARKER_PREFIX + "stuschedule" + "-->" + stu() +
        JwBjtuParser.DOC_MARKER_PREFIX + "schedule" + "-->" + sched()

    private fun loginCombined(): String =
        JwBjtuParser.DOC_MARKER_PREFIX + "stuschedule" + "-->" + login() +
        JwBjtuParser.DOC_MARKER_PREFIX + "schedule" + "-->" + sched()

    private fun tr(s: Int, e: Int, t: Int) = Triple(s, e, t)

    private fun runsOf(text: String) = JwBjtuParser.parseWeekRuns(text)
        .map { Triple(it.startWeek, it.endWeek, it.type) }

    // ---- A. week grammar ----

    @Test
    fun `week grammar table`() {
        val cases: List<Pair<String, List<Triple<Int, Int, Int>>>> = listOf(
            "第01-16周" to listOf(tr(1, 16, 0)),
            "第1-16周(单)" to listOf(tr(1, 15, 1)),
            "第1-16周（双）" to listOf(tr(2, 16, 2)),
            "第2,4,6周" to listOf(tr(2, 6, 2)),
            "第3周" to listOf(tr(3, 3, 0)),
            "第1-4,6-10周" to listOf(tr(1, 4, 0), tr(6, 10, 0)),
            "第1-8周 第9-16周" to listOf(tr(1, 8, 0), tr(9, 16, 0)),
            "主校区, 主区, 3-302" to emptyList(),
            "第01-16周 单老师" to listOf(tr(1, 16, 0)),
            "第01-16周(单) 张三 主校区, 主区, 9-101" to listOf(tr(1, 15, 1)),
        )
        for ((text, expected) in cases) {
            assertEquals("text=[$text]", expected, runsOf(text))
        }
    }

    // ---- B. stuschedule 端到端 (本学期课表, 5 课) ----

    @Test
    fun `stuschedule parses 5 courses with exact fields`() {
        val courses = JwBjtuParser(stu()).generateCourseList()
        assertEquals(5, courses.size)
        val math = courses.single { it.name == "高等数学A(上)" }
        assertEquals(1, math.day)
        assertEquals(1, math.startNode)
        assertEquals(2, math.endNode)
        assertEquals(1, math.startWeek)
        assertEquals(16, math.endWeek)
        assertEquals(JwBjtuParser.TYPE_DEFAULT, math.type)
        assertEquals("张三", math.teacher)
        assertEquals("主校区, 主区, 3-302", math.room)
        val eng = courses.single { it.name == "大学英语III" }
        assertEquals(2, eng.day)
        assertEquals(3, eng.startNode)
        assertEquals(4, eng.endNode)
        assertEquals(1, eng.startWeek)
        assertEquals(15, eng.endWeek)
        assertEquals(JwBjtuParser.TYPE_ODD, eng.type)
        assertEquals("李梅", eng.teacher)
        assertEquals("主校区, 主区, 8-201", eng.room)
        val pe = courses.single { it.name == "体育IV" }
        assertEquals(4, pe.day)
        assertEquals(5, pe.startNode)
        assertEquals(5, pe.endNode)
        assertEquals(1, pe.startWeek)
        assertEquals(16, pe.endWeek)
        assertEquals(JwBjtuParser.TYPE_DEFAULT, pe.type)
        assertEquals("主校区, 东校区, 田径场", pe.room)
        val ds = courses.single { it.name == "数据结构" }
        assertEquals(3, ds.day)
        assertEquals(6, ds.startNode)
        assertEquals(7, ds.endNode)
        assertEquals(1, ds.startWeek)
        assertEquals(16, ds.endWeek)
        assertEquals("王强", ds.teacher)
        assertEquals("主校区, 主区, 9-101", ds.room)
        val os = courses.single { it.name == "操作系统" }
        assertEquals(5, os.day)
        assertEquals(6, os.startNode)
        assertEquals(7, os.endNode)
        assertEquals(10, os.startWeek)
        assertEquals(17, os.endWeek)
        assertEquals(JwBjtuParser.TYPE_DEFAULT, os.type)
        assertEquals("孙敏", os.teacher)
        assertEquals("主校区, 主区, 2-105", os.room)
    }

    // ---- C. schedule 端到端 (选课任务课表/全学期, 8 课) ----

    @Test
    fun `schedule parses 8 courses incl multi-teacher and parity runs`() {
        val courses = JwBjtuParser(sched()).generateCourseList()
        assertEquals(8, courses.size)
        val eng = courses.filter { it.name == "大学英语III" }.sortedBy { it.startWeek }
        assertEquals(2, eng.size)
        assertEquals(2, eng[0].day)
        assertEquals(1, eng[0].startNode)
        assertEquals(2, eng[0].endNode)
        assertEquals(1, eng[0].startWeek)
        assertEquals(8, eng[0].endWeek)
        assertEquals("王五", eng[0].teacher)
        assertEquals(9, eng[1].startWeek)
        assertEquals(16, eng[1].endWeek)
        assertEquals("赵六", eng[1].teacher)
        assertEquals("主校区, 主区, 8-105", eng[0].room)
        val lin = courses.single { it.name == "线性代数" }
        assertEquals(2, lin.day)
        assertEquals(3, lin.startNode)
        assertEquals(3, lin.endNode)
        assertEquals(1, lin.startWeek)
        assertEquals(15, lin.endWeek)
        assertEquals(JwBjtuParser.TYPE_ODD, lin.type)
        val lab = courses.single { it.name == "数据结构实验" }
        assertEquals(5, lab.day)
        assertEquals(3, lab.startNode)
        assertEquals(4, lab.endNode)
        assertEquals(6, lab.startWeek)
        assertEquals(13, lab.endWeek)
        val comp = courses.single { it.name == "计算机组成原理" }
        assertEquals(1, comp.day)
        assertEquals(6, comp.startNode)
        assertEquals(7, comp.endNode)
        assertEquals(2, comp.startWeek)
        assertEquals(12, comp.endWeek)
        assertEquals(JwBjtuParser.TYPE_EVEN, comp.type)
        assertEquals("郑浩", comp.teacher)
        assertEquals("主校区, 9-105", comp.room)
    }

    // ---- D. combined adjudication + confidence + features ----

    @Test
    fun `combined doc adjudicates to schedule section`() {
        val parser = JwBjtuParser(combined())
        val courses = parser.generateCourseList()
        assertEquals(8, courses.size)
        assertTrue(courses.any { it.name == "计算机组成原理" && it.type == JwBjtuParser.TYPE_EVEN })
    }

    @Test
    fun `combined doc confidence and features`() {
        val parser = JwBjtuParser(combined())
        assertEquals(95, parser.confidence())
        val features = parser.matchedFeatures()
        assertTrue(features.contains("bjtu:combined-doc"))
        assertTrue(features.contains("path:stuschedule"))
        assertTrue(features.contains("path:schedule"))
        assertTrue(features.contains("th:星期一"))
        assertTrue(features.contains("cell:第N节"))
        assertTrue(features.contains("cell:[HH:MM-HH:MM]"))
    }

    // ---- E. negatives: login / foreign protocol / plain page ----

    @Test
    fun `login page yields zero courses with guard feature`() {
        val parser = JwBjtuParser(login())
        assertEquals(0, parser.generateCourseList().size)
        assertEquals(0, parser.confidence())
        assertTrue(parser.matchedFeatures().contains("guard:login-page"))
    }

    @Test
    fun `combined doc skips login section and keeps schedule`() {
        val parser = JwBjtuParser(loginCombined())
        assertEquals(8, parser.generateCourseList().size)
    }

    @Test
    fun `zf foreign page rejected by foreign anchor guard`() {
        val parser = JwBjtuParser(zfForeign())
        assertEquals(0, parser.generateCourseList().size)
        assertEquals(0, parser.confidence())
        assertTrue(parser.matchedFeatures().contains("guard:foreign-anchor"))
    }

    @Test
    fun `plain page without table header parses empty`() {
        val html = "<html><body><p>学号: 20210001</p></body></html>"
        val parser = JwBjtuParser(html)
        assertEquals(0, parser.generateCourseList().size)
        assertEquals(0, parser.confidence())
    }

    // ---- F. cross-language invariant (SOP 铁律 3) ----

    private fun srcOf(rel: String): String {
        for (base in listOf(File("app/src/main/java"), File("src/main/java"))) {
            val f = File(base, rel)
            if (f.isFile) return f.readText()
        }
        throw IllegalStateException("source not found: $rel")
    }

    private fun literalOf(src: String, constName: String): String {
        val key = constName + " = \""
        val start = src.indexOf(key)
        require(start >= 0) { "const not found: $constName" }
        val from = start + key.length
        val end = src.indexOf('"', from)
        return src.substring(from, end)
    }

    @Test
    fun `kotlin regex sources equal js regexp literals char by char`() {
        val parserSrc = srcOf("com/lingion/sleepy/data/jw/JwBjtuParser.kt")
        val jsSrc = srcOf("com/lingion/sleepy/ui/screen/imports/JwWebViewLoginScreen.kt")
        val label = literalOf(parserSrc, "PERIOD_LABEL_RE_SRC")
        val time = literalOf(parserSrc, "PERIOD_TIME_RE_SRC")
        assertTrue(label.isNotEmpty())
        assertTrue(jsSrc.contains("new RegExp('" + label + "')"))
        assertTrue(jsSrc.contains("new RegExp('" + time + "')"))
        val stuPath = literalOf(parserSrc, "PATH_STUSCHEDULE")
        val schedPath = literalOf(parserSrc, "PATH_SCHEDULE")
        assertTrue(jsSrc.contains(stuPath))
        assertTrue(jsSrc.contains(schedPath))
        assertTrue(jsSrc.contains(literalOf(parserSrc, "HOST_SUFFIX")))
        val marker = literalOf(parserSrc, "DOC_MARKER_PREFIX")
        assertTrue(jsSrc.contains(marker + "stuschedule"))
        assertTrue(jsSrc.contains(marker + "schedule"))
    }

    // ---- G. registry routing ----

    @Test
    fun `registry routes bjtu type to JwBjtuParser`() {
        val parser = JwParserRegistry.parserFor(JwProtocol.TYPE_BJTU, combined())
        assertTrue(parser is JwBjtuParser)
    }

    @Test
    fun `selectBest with declared bjtu type returns 8 courses`() {
        val (courses, attempts) = JwParserRegistry.selectBest(combined(), JwProtocol.TYPE_BJTU)
        assertEquals(8, courses.size)
        val bjtu = attempts.firstOrNull { it.type == JwProtocol.TYPE_BJTU }
        assertTrue(bjtu != null)
        assertEquals(8, bjtu!!.courseCount)
        assertEquals(95, bjtu.confidence)
    }
}
